### ISSUE TITLE
As a user, I want to know how to set up the webhook

### ISSUE THREAD

**Issue by afeld** [18F/federalist-docs#10]

**Comment by wslack** [comment]
@afeld would this be satisfied by documentation explaining how to set up the hook manually or explaining what Federalist does when you add a repo to it?

**Comment by jmhooper** [comment]
Setting up a webhook manually is untenable for external users since doing so requires Federalist's webhook secret.

**Comment by afeld** [comment]
Was the webbook supposed to be added automatically? I assume I filed this because that wasn't the case (for me, at that time).

**Comment by jmhooper** [comment]
Yes, whenever a user adds a site the webhook should be created.

**Comment by afeld** [comment]
> Federalist's webhook secret

Meaning there's only one of them? You may want to consider doing one per repository, to reduce the surface area.

**Comment by jmhooper** [comment]
Agreed. I'll open an issue for that now.

**Comment by afeld** [comment]
K, since this issue was opened due to a fluke that's presumably gone if no one else has mentioned it, I'll close this.
