### ISSUE TITLE
Specify value of NODE_ENV when `npm run federalist` is run?

### ISSUE THREAD

**Issue by toolness** [18F/federalist-docs#111]
I realized that it'd be nice if my site built using a production configuration when running on Federalist, which made me wonder if `NODE_ENV` is set to `production` or anything. If it's not, that's ok--I can just modify my `federalist` NPM script to e.g. set that environment variable, or something else. But if it does, it'd be nice to document that in the Federalist node docs!

**Comment by jseppi** [comment]
`NODE_ENV` is not set anywhere in the build container currently. Here's the node section of stuff in the script: https://github.com/18F/federalist-garden-build/blob/staging/build.sh#L36-L57

**Comment by toolness** [comment]
Ah ok, cool, thanks! I guess I will just close this issue then.
