### ISSUE TITLE
Responsive break seems too wide 

### ISSUE THREAD

**Issue by awfrancisco** [18F/federalist-docs#120]
The break for https://federalist-docs.18f.gov/ to switch to a tablet layout seems too wide. If the window is even slightly narrower that full screen on my laptop, the side nav drops to the bottom of the page, which hides a lot of the page content. 

This fix is above my technical level, but it seems like the break happens much earlier than on other 18F sites.

**Comment by wslack** [comment]
This is caused by the way that Shawn Allen implemented the USWDS. Moving the site to a new template is a large lift so this isn't prioritized ATM.

**Comment by line47** [comment]
I'd like to bring the overall Federalist site and docs site in closer alignment in terms of branding and pull the design from Federalist over to the documentation site.

**Comment by wslack** [comment]
The feedback we've gotten content wise is that using a separate site is confusing to people (even though I think its important to have it for the sake of dogfooding).

What do you think about focusing on building out new sales-focused pages on federalist.18f.gov first?

**Comment by line47** [comment]
The USWDS-Jekyll theme and also this federalist docs site which is using said theme are built off of the USWDS Grid and the left hand navigation rolls off at 1200px because of the way the left hand navigation is structured. The HTML for the way the left navigation is built into the templates would need to be altered similar to the USWDS documentation site. https://standards.usa.gov/components/

**Comment by line47** [comment]
The federalist docs site needs to be updated to use the latest uswds-jekyll and this will fix the breakpoint issue

**Comment by wslack** [comment]
Yep - but I think this is a large lift, right?

**Comment by line47** [comment]
- Adjusting the breakpoint is one issue (I'll be putting in a PR for this)

- Making the side nav go into the off canvas is a separate issue and one that should be addressed a the USWDS level (no know issue for it yet)
