### ISSUE TITLE
Add search to federalist-docs site

### ISSUE THREAD

**Issue by jseppi** [18F/federalist-docs#123]
I personally am often frustrated by not being able to search our docs website. I often resort to using my code editor's find functionality to search my local clone of this repo. Integrating search in the site itself would be really nice.

I'm not very familiar with the landscape, but I think some options are:

- Digital.gov search (ref https://github.com/18F/federalist-docs/issues/85)
  - This seems like a pretty nice option to me
  - further notes: https://docs.google.com/document/d/1wG2tbJJ9u26nDRAlTnyvruTScTMHsGV5pykXzBHN_aU/edit#
- Some kind of jekyll-lunr.js integration

**Comment by wslack** [comment]
We should update our style a la partnership-playbook.18f.gov to use the lunr.js search.

**Comment by jseppi** [comment]
Got a link to what you mean? I don't see any search functionality at https://partnership-playbook.18f.gov/

**Comment by wslack** [comment]
I changed the link 🖌

**Comment by wslack** [comment]
See https://docs.google.com/document/d/1fY2jgL_u60JCVi90VDoizthif446QipkVYRrr4vdyG0/edit#bookmark=id.gr9tx76yojyv for instructions

**Comment by jseppi** [comment]
Any reason you prefer that plugin to the digitalgov-search service? I seem to recall that using the lunr plugin was causing a lot of headaches during migration (something about not playing well with newer jekyll versions -- https://docs.google.com/document/d/1fY2jgL_u60JCVi90VDoizthif446QipkVYRrr4vdyG0/edit#bookmark=id.7m9jdlyqpo8u).

**Comment by wslack** [comment]
I'm agnostic.

**Comment by wslack** [comment]
Also Shawn pulled this repo away from guides-style: https://github.com/18F/federalist-docs/pull/31/files

**Comment by wslack** [comment]
As we do this, want to make it *super* easy for someone to add search to their template.
