### ISSUE TITLE
Add a basic diagram to help with Federalist Sales

### ISSUE THREAD

**Issue by wslack** [18F/federalist-docs#130]
#### Description of feature or bug

Someone non-technical that wants to "get" Federalist would do better with a very basic diagram of the entire system.

#### Definition of done

- [x] New diagram is added to the docs repo
#
_After evaluating, edit this part:_

**Comment by wslack** [comment]
We should also explore ways of making the GitHub screens less of a surprise and having a place to explain them to the user.

**Comment by wslack** [comment]
https://federalist-docs.18f.gov/pages/how-federalist-works/

**Comment by wslack** [comment]
Current ATO diagram: https://github.com/18F/federalist/issues/903#issuecomment-357088328

Current docs site diagram: https://federalist-docs.18f.gov/assets/images/Federalist%20System%20Diagram%2011-28-16.png

**Comment by ericronne** [comment]
Here's a very-simple first crack at this, essentially a conversation starter. Received some additional input from @jseppi, who should in no way be held accountable for any mis-information included herein.

![system-diagram-basic-v0 1](https://user-images.githubusercontent.com/9259185/36111754-ccf9b796-0fec-11e8-8505-fadf7ec3f957.png)

**Comment by jseppi** [comment]
oooh, nice!

I think `yoursite.gov` is also `✅ Covered by Federalist ATO`

`Hosted on cloud.gov on Amazon Web Services`. Too many `on`s? Maybe `Hosted by cloud.gov` is ok too.

Maybe a tagline for "Federalist S3 bucket" that says something like `Stores your site files`.

I'd also connect "Preview website" to the "Federalist" box instead of to the bucket, because those also go through `federalist-proxy` (which is a component of the "Federalist" box).

**Comment by ericronne** [comment]
Revision. If previews should be linked to the "Federalist" box, is the S3 bucket the "Preview-site server"?

![system-diagram-basic-v0 2](https://user-images.githubusercontent.com/9259185/36113986-3e2c93dc-0ff4-11e8-9992-f6ebcb2cdebc.png)

**Comment by jseppi** [comment]
No, I'd scrap the `Preview-site server` text

Maybe it could be replaced with something like `Production site, demo site, and preview builds`

**Comment by ericronne** [comment]
If it's essentially a storage bin, might this reflect all the average potential customer would need to know? ...

![system-diagram-basic-v0 3](https://user-images.githubusercontent.com/9259185/36114301-476a5186-0ff5-11e8-9a8b-cb0d8033ac99.png)

**Comment by jseppi** [comment]
Yeah, I think that simplification is good. Maybe remove the bit about `builds` since those aren't really a specific artifact that is stored.

**Comment by ericronne** [comment]
Cool. Rephrased:

![system-diagram-basic-v0 4](https://user-images.githubusercontent.com/9259185/36114824-c4a4f63c-0ff6-11e8-8f89-e63b2b43d080.png)

**Comment by wslack** [comment]
I like so much!

- Don't think we need the AWS logo
- I wonder if its worth showing the proxy here as a separate box to represent that "federalist" doesn't do the hosting. The bifurcation helps people get the compliance argument.
- I would check off everything as "part of Federalist ATO" since it all is involved in the system.

**Comment by ericronne** [comment]
Layout not final, but here's a version incorporating those ☝️ notes, along with other improvements(?) …

![system-diagram-basic-v0 5](https://user-images.githubusercontent.com/9259185/36171823-abb9559a-10c9-11e8-8c71-9cba3c0aeb85.png)

**Comment by jseppi** [comment]
My opinion on this is that to keep this diagram high-level/simple we should just have one box for Federalist (the system). This box would logically comprise `federalist-core`, `federalist-builder`, `federalist-garden-build`, and `federalist-proxy`, even though the diagram shouldn't spell out that level of detail.

`proxy` especially sounds very technical to me. I'm skeptical the audience we're targeting with this diagram would know it means, or care.

**Comment by wslack** [comment]
I agree that proxy is technical sounding BUT I feel like its important to also communicate that Federalist-the-box isn't part of the hosting path.

Instead, the S3 bucket would point at the proxy, which would point at bot the live and preview boxes. Federalist and the proxy boxes wouldn't connect.

Maybe we call the proxy something else like "Federalist hosting service" and say it includes a proxy and cloudfront?

**Comment by ericronne** [comment]
Is "cloudfront" an essential term, or might this version suffice for testing? …
![system-diagram-basicv0 6](https://user-images.githubusercontent.com/9259185/36175589-9f6e186e-10d5-11e8-984a-21dcfb6c1ad5.png)


_props to @jseppi for sage input_

**Comment by wslack** [comment]
We don't need to say "cloudfront" - the above works if we don't want to say "hosting service" instead of "proxy server." 

@shannonbad happy for your ideas here as well.

**Comment by ericronne** [comment]
"Hosting service" sounds good to me

**Comment by ericronne** [comment]
If that's accurate?

**Comment by wslack** [comment]
I'm good with it and I don't think there's an official term.

**Comment by ericronne** [comment]
I shuffled things around a bit, for the sake of simplicity (eg all arrows are now straight). Will do a PR momentarily; please continue the convo over there!

![how-federalist-works-diagram-v1 0](https://user-images.githubusercontent.com/9259185/36282789-edd7801a-1267-11e8-96a0-b1a59163aa1f.png)

**Comment by wslack** [comment]
I LOVE THIS!

**Comment by ericronne** [comment]
Hey i couldn't leave well enough alone, so i created a "minimalist" version. I think it's better: less ink (both "digital" and literal), friendlier to mobile, and simpler overall. Along with design changes, please note slightly modified text in bottom-right panel, which now reads, "Official website" / "Your live site". This felt like it paired better with "Preview websites" to me.

If this is 👍, i'll update the PR
![how-federalist-works-diagraminimal](https://user-images.githubusercontent.com/9259185/36318862-b6bbb570-1306-11e8-9d97-9c37028fb5d8.png)

**Comment by jseppi** [comment]
beautiful!

**Comment by wslack** [comment]
I love this AND I think if we reverse the vertical order it will be clearer. I also like having both images in the docs repo so they can be used in different presentations. (I think the minimal ink version won't show up as clearly on a projector)

**Comment by ericronne** [comment]
Agreed re projection: that should use a different design (wide, with fills, probably reversed type). Will create a separate version for that.

I think top-to-bottom (A) is more clear. Test?

![image](https://user-images.githubusercontent.com/9259185/36320761-e1d22766-130c-11e8-8741-b3c4ddd555f6.png)

**Comment by ericronne** [comment]
Also uploaded this horizontal version, to use in presentations.

![how-federalist-works-for-presentation](https://user-images.githubusercontent.com/9259185/36329672-69d5e78c-132c-11e8-95e9-b08be8f73e17.png)

**Comment by wslack** [comment]
Noting we discussed in standup and @ericronne carried the day!

**Comment by wslack** [comment]
Should go into "Done?"

**Comment by ericronne** [comment]
will get used to this zenbhub bizness some day, some day …
