### ISSUE TITLE
Publish info from this week's meeting with a possible customer

### ISSUE THREAD

**Issue by wslack** [18F/federalist-docs#131]
- [ ] Edit docs site to have this information.

Cost of an ATO for a website: 95K
Cost of an ATO with a pentest: 135K

**Comment by wslack** [comment]
@davidewarren to synthesize in the discussion of Federalist's benefits

**Comment by davidewarren** [comment]
@wslack - the 95K, 135K information is already on the federalist docs - why use federalist page here - https://federalist-docs.18f.gov/pages/about-federalist/why-use-federalist/

**Comment by wslack** [comment]
Oh wow, you're right! This can be moved to "Done?"

**Comment by davidewarren** [comment]
yes, I'll move it
