### ISSUE TITLE
Indicate that repos used in Federalist must be public

### ISSUE THREAD

**Issue by jseppi** [18F/federalist-docs#136]
I didn't find this noted anywhere. A good place to put it is probably the "Adding a new site" section of "Using Federalist."

**Comment by wslack** [comment]
@jseppi they don't have to be, though? you could have a private repo (and private issues and such) while knowing that previews are public.

**Comment by jseppi** [comment]
Hrm...I guess I don't know! We had a user this morning not able to build from a private repo. Maybe the fact that it was private wasn't the root problem?

**Comment by wslack** [comment]
nope. Federalist routinely has supported private repos (unless we changed something I didn't know about).
