### ISSUE TITLE
Style the search.gov results page

### ISSUE THREAD

**Issue by wslack** [18F/federalist-docs#143]
Apply styling to search.gov results page to match the styling of the Federalist Docs site.

**Comment by line47** [comment]
Updated search results - let me know if you want any other changes

### Screenshot
![screen shot 2017-12-13 at 11 24 20 am](https://user-images.githubusercontent.com/1449852/33949394-7838659c-dff7-11e7-923b-6eecfa6c46b3.png)

**Comment by jseppi** [comment]
Looks good to me!

**Comment by line47** [comment]
closing this issue for now
