### ISSUE TITLE
clicking on title of docs site does not take me back to the homepage

### ISSUE THREAD

**Issue by wslack** [18F/federalist-docs#144]
I just checked and it looks like some old builds of Federalist had this issue:

https://federalist-proxy.app.cloud.gov/preview/18f/federalist-docs/update-clair-instructions/pages/using-federalist/instructional-demos/

Not sure when it was introduced or how to make the title text link back to the homepage.

**Comment by jseppi** [comment]
I can fix

**Comment by jseppi** [comment]
Looks like it has been that way for 10 months:

<img width="749" alt="screen shot 2017-10-06 at 12 16 26 pm" src="https://user-images.githubusercontent.com/697848/31294576-3d611884-aa90-11e7-8694-ba9d7ea5f18c.png">
