### ISSUE TITLE
Add info or pointer about available environment variables during site builds

### ISSUE THREAD

**Issue by jseppi** [18F/federalist-docs#175]
Probably should go in the https://federalist-docs.18f.gov/pages/how-federalist-works/how-builds-work/ section.

We could just point to the associated section of the federalist-garden-build-py README: https://github.com/18f/federalist-garden-build-py#variables-exposed-during-builds

Thoughts, @wslack?

**Comment by wslack** [comment]
That sounds good to me. Are you saying they can be called directly, or are they all grouped under a "federalist" tag?

**Comment by wslack** [comment]
Like, if the site builder wants to use those variables on its own, this could be messy - so I like putting them all as subvariables as seen in a Jekyll config file. Hopefully that makes sense....
