### ISSUE TITLE
Template images are broken

### ISSUE THREAD

**Issue by jseppi** [18F/federalist-docs#178]
On https://federalist-docs.18f.gov/pages/using-federalist/templates/

Cause: the template images are served from at https://federalist.18f.gov and they were renamed as part of https://github.com/18F/federalist/pull/1295

<img width="1258" alt="screen shot 2017-11-21 at 3 50 14 pm" src="https://user-images.githubusercontent.com/697848/33098649-c14800e2-ced3-11e7-9ef7-a8fa7830ebbb.png">

**Comment by jseppi** [comment]
The new thumbnail images on https://federalist.18f.gov/sites/new are actually thumbnails now though, so they won't look good as full size images.

Suggest that the images desired be brought over to this repo instead of using the images served by https://federalist.18f.gov

**Comment by wslack** [comment]
kk makes sense since they are now real thumbnails

**Comment by line47** [comment]
This was fixed, closing 📕

**Comment by jseppi** [comment]
Thanks!
