### ISSUE TITLE
Document that the github pages gem interferes with Federalist builds

### ISSUE THREAD

**Issue by wslack** [18F/federalist-docs#220]
#### User Story

As a user working with Federalist, I am blocked from completing builds when I use the Github-Pages gem! I need a way to know that might be an issue and to check for it.

#### Background (Optional)

This has been a technical blocker for multiple partners. We want to add a "so my build don't work" set of things to check for partners.

#### Acceptance Criteria

- [ ] Support content added as a subsection here: https://federalist-docs.18f.gov/pages/using-federalist/support/

_After evaluating, edit this part:_

**Comment by el-mapache** [comment]
@wslack I'm fairly certain that the `github-pages` gem _always_ interferes! I think that since we don't care about publishing sites on GitHub Pages, the docs should tell users to remove references to that gem from their repos.
