### ISSUE TITLE
Wrap glossary terms

### ISSUE THREAD

**Issue by el-mapache** [18F/federalist-docs#237]
Using the list of words and locations of those generated as a part of https://github.com/18F/federalist/issues/1799, go through and wrap each of those words with the appropriate html.

For example:
```
<span data-term="ATO" class="term">ATO</span>
```

The values for  the`data-term` property can be found in `glossary.js`, in the `definitions` variable.

**Comment by wslack** [comment]
Moved content to https://github.com/18f/federalist/issues/1768, closing
