### ISSUE TITLE
Stop using or reconfigure guides_style on federalist-docs

### ISSUE THREAD

**Issue by wslack** [18F/federalist-docs#26]
https://github.com/18F/guides-style forces the "edit this page" link at the bottom to point to an incorrect branch and a `Hosted on 18F Pages` message. We should reconfigure to avoid these issues or stop using the gem.

I think there are three places in code that call this:

- https://github.com/18F/federalist-docs/blob/master/assets/css/styles.scss
- https://github.com/18F/federalist-docs/blob/master/go
- https://github.com/18F/federalist-docs/blob/master/_config.yml

**Comment by afeld** [comment]
Shouldn't be too hard to make configurable: https://github.com/18F/guides-style

**Comment by wslack** [comment]
Being done in https://github.com/18F/federalist-docs/pull/31
