### ISSUE TITLE
(WIP) Content to add about editing the main Federalist template

### ISSUE THREAD

**Issue by wslack** [18F/federalist-docs#27]
- The main Federalist template builds pages using layouts with pre-made headers and footers, all created with HTML. These templates cannot be edited though the Federalist editor and must be modified by someone with knowledge of HTML.
- Some of the text on pages is adjusted using the front matter, not the text editing interface.
- Pages have titles, filenames, and names in the menu, which can all be configured separately.
- Files should be uploaded on different branches than those creating links to the files.
- Uploading files in bulk works best using a GitHub client that syncs between your local machine and GitHub

**Comment by jseppi** [comment]
This looks like it is referencing the now-defunct editor in Federalist.

**Comment by wslack** [comment]
correct, closing
