### ISSUE TITLE
Document solution for: I want to use a template, and have a repo in the 18F org

### ISSUE THREAD

**Issue by zacharycohn** [18F/federalist-docs#39]
I was trying to spin up a new site on federalist today and couldn't figure out how to use one of the provided templates and also connect it to a repo in the 18F org. 

Will Slack provided the answer (use the "Use this template/Create this site" button which creates a repo in your personal github account, move your repo from your personal account to the 18F org, delete the site off Federalist, re-add it using the "Or add your own Github repository" option). 

It would be great if this workflow was included in the federalist support docs somewhere

**Comment by jmhooper** [comment]
Note that #571 is in the backlog which would allow specification of an org when creating a site from a template.

**Comment by wslack** [comment]
@jmhooper how easy would it be to allow this? I worry about the number of edge cases where people try to create repos they aren't allowed to.

We should certainly have the workflow spelled out though.

**Comment by jmhooper** [comment]
I'll add a reply to 18F/federalist#571 so that we can refer to it there.

**Comment by wslack** [comment]
This issue is specifically for the documentation need

**Comment by jmhooper** [comment]
PR #762 added an "Owner" text field to the templates in the Add Site view which should mean there's no longer a documentation need here.

**Comment by wslack** [comment]
@zacharycohn want to try out our fix on staging and see if it resolves your concern?

**Comment by wslack** [comment]
We just tested and confirmed this was fixed in #762 in github.com/federalist.
