### ISSUE TITLE
Landing Page template image not displaying

### ISSUE THREAD

**Issue by oghaffari** [18F/federalist-docs#44]
# Description

The image under the heading "Landing Page for Information about a Released Report" is not displaying.

# Steps to reproduce the issue

1. Go here: https://federalist-docs.18f.gov/pages/using-federalist/#federalist-templates
2. Scroll to the second template.

# Additional information [optional]

Screen shot:

![screen shot 2017-01-18 at 2 36 25 pm](https://cloud.githubusercontent.com/assets/10715995/22081865/f2df9088-dd8a-11e6-908d-487929627e0a.png)

**Comment by wslack** [comment]
Fixed by https://github.com/18F/federalist/commit/75f83f357515105930b69e9351d38cee0bc73b27 ( cc @jmhooper as an example of something that burned us in moving from master)

**Comment by wslack** [comment]
Thank you @oghaffari!
