### ISSUE TITLE
Update federalist-docs to use new guides_style gem

### ISSUE THREAD

**Issue by konklone** [18F/federalist-docs#48]
I can't find where in the code/data this is set to file a PR for, but the "Edit this page" link, on the bottom of pages like this one, is broken:

https://federalist-docs.18f.gov/pages/using-federalist/customer-responsibilities/

It links to `https://github.com/18F/federalist-docs/edit/18f-pages/pages/using-federalist/customer-responsibilities.md`, but the correct link replaces `18f-pages` with `master`.

Also, the text in the footer says "Hosted on 18F Pages", which is now incorrect.

**Comment by wslack** [comment]
@konklone this is tied to the use of the 18f_guides_style gem that many of our guides use. See https://github.com/18F/guides-style/issues/23

Someone will need to change the guides style then update the gem used by all of the guides and such.

**Comment by wslack** [comment]
I realize this is annoying; we're actually going to move to this branch on this repo but its still a general issue: https://federalist.18f.gov/preview/18f/federalist-docs/uswds/
