### ISSUE TITLE
Document how to include USWDS SASS into Federalist site

### ISSUE THREAD

**Issue by line47** [18F/federalist-docs#52]
I'd like to incorporate the USWDS into a federalist Jekyll site but have not found any documentation on how to do this.

**Comment by wslack** [comment]
@line47 is this something that Federalist should tell you how to do, or should the USWDS team own this? cc @yowill

**Comment by line47** [comment]
I think it would be nice to have this as an option to use the USWDS baked into Federalist. 
I think info on getting the SASS implemntation to work within Jekyll would be found on the USWDS site.

**Comment by wslack** [comment]
> to use the USWDS baked into Federalist.

There are no USWDS baked into Federalist. Federalist has some templates that could use the USWDS if you or others want to add in more to the templates (or modify templates), but Federalist-the-product is agnostic about content or template.

**Comment by wslack** [comment]
However, I get the desire for more templates if that's what you want.

**Comment by jseppi** [comment]
Worth closing since this is out-of-scope for Federalist itself? USWDS docs have some info on using its SASS files: https://standards.usa.gov/getting-started/developers/#customization-and-theming
