### ISSUE TITLE
Add frames to example site screenshots

### ISSUE THREAD

**Issue by wslack** [18F/federalist-docs#70]
re: https://github.com/18F/federalist/issues/817

https://federalist-docs.18f.gov/pages/about-federalist/example-sites/

**Comment by line47** [comment]
Is this issue still active @wslack ?
I'm trying to go through the docs site issues and address what I can with this UI PR update https://github.com/18F/federalist-docs/pull/183.

**Comment by wslack** [comment]
We can close this given the new examples page you made!
