### ISSUE TITLE
Review and clean up README

### ISSUE THREAD

**Issue by jseppi** [18F/federalist-docs#76]
It still references 18f-pages, for example.

**Comment by jseppi** [comment]
Oh, it is an old version of a README copied from guides-style or something, so it is all kinds of out-of-date.

**Comment by wslack** [comment]
@jseppi reminder - don't close issues. Instead, they go into "Done."

**Comment by jseppi** [comment]
Oh whoops, thought that was only for the main federalist repo. My mistake!

**Comment by wslack** [comment]
all 10 of them please!
