### ISSUE TITLE
Methods Cards as example site

### ISSUE THREAD

**Issue by nickykrause** [18F/federalist-docs#90]
Hey! The methods cards are in Federalist now - might be a good candidate for your list of examples.

homepage screenshot:
<img width="1253" alt="screen shot 2017-06-12 at 10 58 09 am" src="https://user-images.githubusercontent.com/1450173/27042970-3ac63614-4f5e-11e7-831c-2664701d8ffb.png">

**Comment by wslack** [comment]
Task: add screenshot to examples site

**Comment by wslack** [comment]
Thanks @nickykrause!
